from django.db import models

USER_FIRST_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 16
USER_ABOUT_MAX_LENGTH = 256
USER_EMAIL_MAX_LENGTH = 254
USER_NAME_MAX_LENGTH = 124
USER_GITHUB_URL_MAX_LENGTH = 200

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_DESCRIPTION_MAX_LENGTH = 5000
PROJECT_GITHUB_URL_MAX_LENGTH = 200

PROJECT_STATUS_OPEN = 'open'
PROJECT_STATUS_CLOSED = 'closed'
PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, 'Open'),
    (PROJECT_STATUS_CLOSED, 'Closed'),
]

MAX_STATUS_LEN = max(
    len(PROJECT_STATUS_OPEN),
    len(PROJECT_STATUS_CLOSED),
)

PAGE_SIZE = 12

