USER_FIRST_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 16
USER_EMAIL_MAX_LENGTH = 254
USER_NAME_MAX_LENGTH = 124
USER_GITHUB_URL_MAX_LENGTH = 200

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_GITHUB_URL_MAX_LENGTH = 200

PROJECT_STATUS_OPEN = 'open'
PROJECT_STATUS_CLOSED = 'closed'
PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, 'Открыт'),
    (PROJECT_STATUS_CLOSED, 'Закрыт'),
]

MAX_STATUS_LEN = max(len(status[0]) for status in PROJECT_STATUS_CHOICES)

PAGE_SIZE = 12

